name: SimpleTAB
version: 1.0.0
main: me.fliqq.simpletab.SimpleTAB
description: Dynamic TAB Plugin Paired With LuckPerms
author: Fliqq
api-version: "1.21.1"
softdepend: [LuckPerms]
commands:
  tabreload:
    description: Reloads the plugin
    usage: /tabreload
    permission: simpletab.reload
