name: CustomHomes
version: 1.0.0
main: me.fliqq.customhomes.CustomHomes
description: Homes per Ranks
author: Fliqq
api-version: 1.21.1
commands:
  sethome:
    description: Sets a home
  home:
    description: Teleport to home
  delhome:
    description: Deletes a home
